# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - alexgdockerbota

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://alexgdocker.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_18be2688bb30408fb9bae0d75a52217e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3d50db8f77fc4e8f90843867f4293fc8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: alexgdocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_18be2688bb30408fb9bae0d75a52217e }}/botaniadocker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'alexgdockerbota'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_44bb88a4423e4538bcbbe634c72a31c5 }}
        images: 'alexgdocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_18be2688bb30408fb9bae0d75a52217e }}/botaniadocker:${{ github.sha }}'